M:rest_screen
F:G$screen_rest_screen_load$0$0({2}DF,SV:S),Z,0,0,0,0,0
F:G$screen_rest_screen_update$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lrest_screen.screen_rest_screen_update$screen_type$1$8({2}DG,SC:U),B,1,4
S:G$engine_content_manager_load_splash$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_tiles$0$0({2}DF,SV:S),C,0,0
S:G$engine_content_manager_load_title$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_char$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_text$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_data$0$0({2}DF,SV:S),C,0,0
S:G$engine_font_manager_zero$0$0({2}DF,SV:S),C,0,0
