M:font_manager
F:G$engine_font_manager_char$0$0({2}DF,SV:S),Z,0,0,0,0,0
S:Lfont_manager.engine_font_manager_char$ch$1$70({1}SC:U),B,1,4
S:Lfont_manager.engine_font_manager_char$x$1$70({1}SC:U),B,1,5
S:Lfont_manager.engine_font_manager_char$y$1$70({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_char$pnt$1$71({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_char$tile$1$71({1}SC:U),R,0,0,[c]
F:G$engine_font_manager_text$0$0({2}DF,SV:S),Z,0,1,0,0,0
S:Lfont_manager.engine_font_manager_text$text$1$72({2}DG,SC:U),B,1,4
S:Lfont_manager.engine_font_manager_text$x$1$72({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_text$y$1$72({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_text$pnt$1$73({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_text$idx$1$73({1}SC:U),B,1,-1
S:Lfont_manager.engine_font_manager_text$ch$2$74({1}SC:U),R,0,0,[b]
S:Lfont_manager.engine_font_manager_text$tile$2$74({1}SC:U),R,0,0,[b]
F:G$engine_font_manager_data$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Lfont_manager.engine_font_manager_data$data$1$75({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_data$x$1$75({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_data$y$1$75({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_data$pnt$1$76({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_data$idx$1$76({1}SC:U),B,1,-6
S:Lfont_manager.engine_font_manager_data$tile$1$76({2}SI:U),R,0,0,[b,e]
S:Lfont_manager.engine_font_manager_data$quotient$1$76({2}SI:U),B,1,-4
S:Lfont_manager.engine_font_manager_data$remainder$1$76({1}SC:U),R,0,0,[c]
S:Lfont_manager.engine_font_manager_data$hold$1$76({3}DA3d,SC:U),B,1,-9
S:Lfont_manager.engine_font_manager_data$sloc0$1$0({2}DD,SC:U),B,1,-2
S:Lfont_manager.engine_font_manager_data$sloc1$1$0({1}SC:U),B,1,-5
S:Lfont_manager.engine_font_manager_data$sloc2$1$0({2}SI:U),B,1,-4
F:G$engine_font_manager_zero$0$0({2}DF,SV:S),Z,0,4,0,0,0
S:Lfont_manager.engine_font_manager_zero$data$1$80({2}SI:U),B,1,4
S:Lfont_manager.engine_font_manager_zero$x$1$80({1}SC:U),B,1,6
S:Lfont_manager.engine_font_manager_zero$y$1$80({1}SC:U),B,1,7
S:Lfont_manager.engine_font_manager_zero$pnt$1$81({2}DG,SC:U),R,0,0,[]
S:Lfont_manager.engine_font_manager_zero$idx$1$81({1}SC:U),B,1,-3
S:Lfont_manager.engine_font_manager_zero$tile$1$81({2}SI:U),R,0,0,[e,d]
S:Lfont_manager.engine_font_manager_zero$hold$1$81({3}DA3d,SC:U),B,1,-6
S:Lfont_manager.engine_font_manager_zero$sloc0$1$0({2}DD,SC:U),B,1,-2
F:Ffont_manager$get_tile$0$0({2}DF,SC:U),Z,0,0,0,0,0
S:Lfont_manager.get_tile$ch$1$84({1}SC:U),B,1,4
S:Lfont_manager.get_tile$tile$1$85({1}SC:U),R,0,0,[]
S:G$devkit_SMS_init$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOnFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPturnOffFeature$0$0({2}DF,SV:S),C,0,0
S:G$devkit_VDPFEATURE_EXTRAHEIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHIFTSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_HIDEFIRSTCOL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LEFTCOLBLANK$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKHSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_LOCKVSCROLL$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_ZOOMSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_USETALLSPRITES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_240LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_224LINES$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_FRAMEIRQ$0$0({2}DF,SI:U),C,0,0
S:G$devkit_VDPFEATURE_SHOWDISPLAY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_displayOn$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_displayOff$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollX$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGScrollY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBackdropColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_useFirstHalfTilesforSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpriteMode$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SPRITEMODE_NORMAL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SPRITEMODE_TALL_ZOOMED$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_mapROMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableSRAMBank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableSRAM$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_SRAM$0$0({2}DF,DG,SC:U),C,0,0
S:G$devkit_SMS_waitForVBlank$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadPSGaidencompressedTiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadTileMapArea$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSTMcompressedTileMap$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST08$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_crt0_RST18$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_XYtoADDR$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatLoc$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextTileatAddr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTileatXY$0$0({2}DF,SV:S),C,0,0
S:G$devkit_TILE_FLIPPED_X$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_FLIPPED_Y$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_USE_SPRITE_PALETTE$0$0({2}DF,SI:U),C,0,0
S:G$devkit_TILE_PRIORITY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_initSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_reserveSprite$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_updateSpritePosition$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_updateSpriteImage$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_hideSprite$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setClippingWindow$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSpriteClipping$0$0({2}DF,SC:S),C,0,0
S:G$devkit_SMS_finalizeSprites$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setBGPaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setSpritePaletteColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextBGColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setNextSpriteColoratIndex$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setColor$0$0({2}DF,SV:S),C,0,0
S:G$devkit_RGB$0$0({2}DF,SC:U),C,0,0
S:G$devkit_RGB8$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_loadBGPaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_loadSpritePaletteHalfBrightness$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroBGPalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_zeroSpritePalette$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_getKeysStatus$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysPressed$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysHeld$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_getKeysReleased$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_UP$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_DOWN$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_LEFT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_RIGHT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_1$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_2$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_KEY_START$0$0({2}DF,SI:U),C,0,0
S:G$devkit_RESET_KEY$0$0({2}DF,SI:U),C,0,0
S:G$devkit_CARTRIDGE_SLOT$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_A_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_PORT_B_TH$0$0({2}DF,SI:U),C,0,0
S:G$devkit_SMS_queryPauseRequested$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_resetPauseRequest$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VDPFlags$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITEOVERFLOW$0$0({2}DF,SC:U),C,0,0
S:G$devkit_VDPFLAG_SPRITECOLLISION$0$0({2}DF,SC:U),C,0,0
S:G$devkit_SMS_setLineInterruptHandler$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setLineCounter$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_enableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_disableLineInterrupt$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemcpy_brief$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemset$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_VRAMmemsetW$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_copySpritestoSAT$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy32$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy64$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_VRAMmemcpy128$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load1Tile$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load2Tiles$0$0({2}DF,SV:S),C,0,0
S:G$devkit_UNSAFE_SMS_load4Tiles$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_isr$0$0({2}DF,SV:S),C,0,0
S:G$dekvit_SMS_nmi_isr$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk8$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_addSprite_bulk12$0$0({2}DF,SV:S),C,0,0
S:G$devkit_SMS_setTilePriority$0$0({2}DF,SV:S),C,0,0
S:G$devkit_isCollisionDetected$0$0({2}DF,SC:U),C,0,0
